### ISSUE TITLE
CI/CD for checking prettier/lint

### ISSUE THREAD

**Issue by mcnaveen** [mcnaveen/liny#14]
### Describe the feature or enhancement

It's a good idea to have a GitHub workflow that checks code styles, lint, and formatting. Husky does that already. But it's not effective.

**Comment by jagadhis** [comment]
Hi @mcnaveen i would like to do this enhancement 

i see that we already have husky, eslint, prettier setup done.

if there is a option to customize this i would suggest lefthook, Eslint stylistic to implement that will be good combination to handle the code styles, linting and formatting

Eslint stylistic(https://eslint.style/guide/getting-started)
Lefthook(https://github.com/evilmartians/lefthook)

also i saw the format of the commit messages you have added can we add commitlint also to this to maintain the format as in future if there is more contribution
Commitlint(https://commitlint.js.org/)

would like to hear your thoughts on this

**Comment by mcnaveen** [comment]
Hi, @jagadhis Great you want to work on this enhancement! Thank you first.

Tbh, Both are kind of unfamiliar to me. This is the first time I've heard these. So I'm open to suggestions.

And yes, I'm following Conventional Commits.

I do have a few questions.

- How does it affect the current setup
- Is making changes beginner-friendly?
- Is it fast?

**Comment by jagadhis** [comment]
@mcnaveen yeah the changes are pretty straight forward 

To answer your questions:

1. How does it affect the current setup
we need to migrate from husky to lefthook that is also a straight forward setup to do , the Stylistic eslint setup might be a hard one to change we have to set the rules as how we wanted and it needs to be changed in every file 

2. Is making changes beginner-friendly?
Yeah they are beginner-friendly just straight forward from the docs for lefthook and commitlint just for Stylistic eslint we need to make changes on the eslintrc.json file

3. Is it fast?
Yeah i am working on a codebase with this setup it is good and helps maintaining a clean codebase and developer experience. That's the reason i was suggesting it since i have seen open source projects once there are lot more contribution it is difficult to maintain the codebase clean.

**Comment by mcnaveen** [comment]
That's awesome @jagadhis Thanks for your answers. Can I assign it to you now?

and, Please join our discord https://discord.gg/Wz2B3wQZCZ

**Comment by jagadhis** [comment]
yeah assign it to me @mcnaveen

**Comment by mcnaveen** [comment]
Just assigned this to you! Looking forward!
